services:
  payments-service-api:
    container_name: payments-api-container
    image: proyectodevopsem/payments-service:latest
    healthcheck:
      test: ["CMD-SHELL", "sleep 1s", "--post-data=''", "http://localhost:8080/payments/1"]
      interval: 5s
      retries: 2

  shipping-service-api:
    container_name: shipping-api-container
    image: proyectodevopsem/shipping-service:latest
    healthcheck:
      test: ["CMD", "wget", "http://localhost:8080/shipping/c"]
      interval: 5s
      retries: 2

  products-service-api:
    container_name: products-api-container
    image: proyectodevopsem/products-service:latest
    healthcheck:
      test: ["CMD", "wget", "http://localhost:8080/products"]
      interval: 5s
      retries: 2
    
  orders-service-api:
    container_name: orders-api-container
    build:
      context: .
      dockerfile: Dockerfile
    image: orders-service
    environment:
      - PAYMENT_SERVICE=http://payments-api-container:8080
      - SHIPPING_SERVICE=http://shipping-api-container:8080
      - PRODUCTS_SERVICE=http://products-api-container:8080
    ports:
      - 8080:8080
    depends_on: 
      payments-service-api:
        condition: service_healthy
      shipping-service-api:
        condition: service_healthy
      products-service-api:
        condition: service_healthy
    healthcheck:
      test: "wget --post-data='[\"123\",\"321\", \"111\"]' --header 'content-type: application/json' http://localhost:8080/orders"
      interval: 5s
      retries: 2
  
  postman:
    container_name: postman-tests-container
    build: 
      context: ./postman
      dockerfile: Dockerfile
    image: postman-tests
    command:
      run orders-service.postman_collection.json -k
      -r cli,htmlextra
      --reporter-htmlextra-export="reports/orders-service-api-tests.html"
    volumes:
      - ./postman:/etc/newman
    depends_on: 
       orders-service-api:
        condition: service_healthy